typescript-language-server/typescript-language-server

- README.md
- src/cli.ts
This PR should fix #17 at some point. It currently only fixes the cli argument handling. I'm counting on @svenefftinge to continue this one.
> [WIP] Fix tsserver logging

- .gitignore
- package.json
- src/document.ts
- src/file-lsp-server.spec.ts
- src/lsp-server.spec.ts
- src/lsp-server.ts
- src/test-utils.ts
- src/tsp-client.spec.ts
- yarn.lock
> documentHighlight should not return occurrences in other documents

- server/src/commands.ts
- server/src/lsp-server.ts
This PR adds a command to apply edits on a file rename. I'm going to test it with Theia.
> apply rename file

- server/package.json
- server/src/diagnostic-queue.ts
- server/src/document.ts
- server/src/lsp-server.ts
- yarn.lock
_+_ debounce triggering diagnostics to avoid spamming tsserver on multiple edits
> fix updating documents on a did change notification

- server/src/diagnostic-queue.ts
- server/src/lsp-server.ts
- server/src/ts-protocol.ts
- server/src/tsp-client.ts
TODO:
It resolves #58 by allowing clients to provide globally installed plugins.
> global plugins support

- server/src/lsp-server.ts
Language server kept logging "Unknown command" despite commands being known.
> Insert missing "else"

- .gitpod.yml
- example/package.json
- scripts/auth.sh
- server/package.json
- yarn.lock
> upgrade to latest monaco

- src/tsp-client.spec.ts
- src/tsp-client.ts
- src/tsp-command-types.ts
We were testing the command that we are not using in the code anymore.
Also refactored a bit the syntax to be more modern and work better with
types.
> Test the "CompletionInfo" command instead of deprecated "Completions"

- src/lsp-server.spec.ts
The original logic appended diagnostic results on each response from the server so we could end up with multiple objects in the array for the same URI. Use Map to match the expected behavior of only retaining the latest results.
> Make diagnostics tests more reliable

- README.md
- src/cli.ts
> fix: remove unsupported --node-ipc and --socket options

- src/lsp-server.ts
- src/utils/api.ts
The tsserver seems to be good at inferring the project configuration when
opening single files without a workspace so don't crash on missing
rootPath.
> feat: support running server on files without root workspace

- README.md
- src/diagnostic-queue.ts
- src/lsp-server.spec.ts
- src/lsp-server.ts
- src/ts-protocol.ts
> feat: ability to ignore diagnostics by code

- README.md
- src/lsp-server.ts
- src/ts-protocol.ts
- src/tsp-client.ts
> feat: add npmLocation option to specify NPM location

- .vscode/launch.json
- package.json
- yarn.lock
Update devDependencies and add linting/testing on commit through husky.
> chore(deps): update dev dependencies (#294)

- package.json
> fix: specify minimum node version to be v12

- src/lsp-server.spec.ts
- src/lsp-server.ts
- src/tsp-client.ts
> fix: exit the server if tsserver process crashes

- src/lsp-server.spec.ts
- src/lsp-server.ts
> fix: respect "includeDeclaration" for references request

- src/utils/modules-resolver.spec.ts
- src/utils/modules-resolver.ts
- src/utils/versionProvider.ts
> fix: lookup workspace typescript in dirs higher up the tree also

- README.md
- src/calls.ts
- src/lsp-server.spec.ts
- src/lsp-server.ts
- yarn.lock
One test related to the "calls" feature is failing.
Not sure what to think of that but on first sight it looks like a regression (at least from the perspective of that feature).
I've [asked in the typescript repo](https://github.com/microsoft/TypeScript/pull/45920#issuecomment-973297518) so will wait for answer before deciding what to do.
> feat: add new preferences from typescript 4.5.3

- src/lsp-server.ts
- src/utils/versionProvider.ts
> fix: add more logging for resolving user-specified tsserver

- README.md
- src/lsp-server.ts
- src/ts-protocol.ts
- src/tsp-client.ts
Add support for passing locale to tsserver
> feat: add support for locale option

- package.json
- src/completion.ts
- src/diagnostic-queue.ts
- src/lsp-server.spec.ts
- src/lsp-server.ts
- src/protocol-translation.ts
- src/test-utils.ts
- src/ts-protocol.ts
- yarn.lock
> fix: snippet completions returned to clients that don't support them

- README.md
- src/commands.ts
- src/features/source-definition.ts
- src/lsp-client.ts
- src/lsp-server.spec.ts
- src/lsp-server.ts
- src/test-utils.ts
- src/tsp-client.spec.ts
- src/tsp-client.ts
- src/tsp-command-types.ts
- test-data/source-definition/a.d.ts
- test-data/source-definition/a.js
- test-data/source-definition/index.ts
> feat: add "Go To Source Definition" command

- src/completion.ts
- src/configuration-manager.ts
- src/lsp-protocol.inlayHints.proposed.ts
- src/lsp-server.spec.ts
- src/lsp-server.ts
- src/ts-protocol.ts
This is something I will need for inlay hints implementation but it also cleans up the code a bit.
> refactor: create ConfigurationManager for handling configuration

- src/completion.ts
- src/lsp-server.spec.ts
- src/lsp-server.ts
- src/ts-protocol.ts
This PR adds insert replace support.
> feat: Add insert replace support for completions

- src/completion.ts
- src/lsp-server.spec.ts
- src/test-utils.ts
> fix: only use optionalReplacementSpan if client supports InsertReplace

- src/tsp-client.ts
Since the `startedLoadingProject` method was not `await`ed, it could happen that `finishedLoadingProject` would be called before `_progressReporter` was created on calling `startedLoadingProject` and it would not cancel the progress that is yet to be created.
`startedLoadingProject` can not be awaited as it's called from tsevent handler so use promises instead.
> fix: loading progress sometimes getting stuck

- README.md
- src/configuration-manager.ts
- src/lsp-server.ts
- src/utils/tsconfig.ts
Also update implicit project configuration defaults to match vscode.
Fixes #602
> feat: add workspace implicit project defaults configuration

- README.md
- src/features/call-hierarchy.spec.ts
- src/features/call-hierarchy.ts
- src/lsp-connection.ts
- src/lsp-server.ts
- src/protocol-translation.ts
- src/test-utils.ts
- src/tsServer/requests.ts
- test-data/call-hierarchy/one.ts
- test-data/call-hierarchy/three.ts
- test-data/call-hierarchy/two.ts
- test-data/tsconfig.json
> feat: implement support for spec version of Call Hierarchy

- src/completion.ts
- src/lsp-server.ts
- src/ts-protocol.ts
Smaller complications payload for clients that don't need those.
> fix(completions): don't set commitCharacters unless client supports those

- src/document.ts
- src/lsp-server.spec.ts
- src/lsp-server.ts
Fixes https://github.com/sublimelsp/LSP-typescript/issues/209
> fix: formatting fails to provide edit at the end of the document
