typescript-language-server/typescript-language-server

- README.md
The badge points to the theia-ide/theia Travis, I guess it should point to theia-ide/typescript-language-server.
> Fix Travis badge URL

- src/lsp-server.ts
When the user closes a file which has some errors/warnings, we currently
leave those diagnostics in place.  However, this language server doesn't
provide diagnostic for closed files.  This means that the diagnostics
won't get updated until the user re-opens that file.  They can therefore
get stale, if the error or warning condition disappears while the file
is closed.
This patch makes it so that when a file is closed, we clear the
diagnostics associated to that file.
Signed-off-by: Simon Marchi <simon.marchi@ericsson.com>
> Clear diagnostics when closing file

- tsconfig.json
When including this package as a dependency of another package, the
Typescript is recompiled as part of the postinstall step.  Some other
modules in node_modules may include some Typescript definition which are
picked up by tsc.  If these files include types unknown when compiling
typescript-language-server (like types from the "dom" library),
compilation will fail with a bunch of errors like:
../@types/jsdom/index.d.ts(19,36): error TS2304: Cannot find name 'DocumentFragment'.
even though these types are not necessary to actually build
typescript-language-server.  This happens for example when using the
master branch of this repo in Theia's typescript extension.
This patch adds "skipLibCheck" to tsconfig.json so that we'll just
ignore these unknown types.
Signed-off-by: Simon Marchi …
> Add skipLibCheck to tsconfig.json

- src/lsp-server.ts
- src/tsp-client.ts
Pull request regarding issue: https://github.com/theia-ide/typescript-language-server/issues/41
According to [1], it seems Microsoft is not planning on supporting formatting configuration on "format".
This PR provides a basic way to support tsfmt.json via the configure command.
We're currently working on our fork, to support the options provided by the textDocument/formatting request from the language server protocol.
Hope this is helpful. If there are any things we need to fix, please let us know.
[1] https://github.com/Microsoft/TypeScript/pull/2468#issuecomment-86085433
> send configure command before formatting command

- src/lsp-server.spec.ts
- src/lsp-server.ts
The promised PR to convert the language server protocol's `FormattingOptions` (`tabSize` and `insertSpaces`) to the tsserver protocol's `FormatCodeSettings` (`indentSize` and `convertTabsToSpaces`).
Should address issue https://github.com/theia-ide/typescript-language-server/issues/10, to a degree, and fully satisfies the original motivation behind issue https://github.com/theia-ide/typescript-language-server/issues/41.
> Document formatting support editor options

- .editorconfig
- package.json
- yarn.lock
Your project is configured to run via yarn, which sadly does not implement the audit feature like npm yet. While trying to get my hands dirty with the repo I figured that there was a critical dependency issue for `command-exists` which is a base dependency, thus all consumers would inherit this issue as well. On that take I've also updated `mocha` to the most recent version to get rid of all vulnerability warnings.
Since mocha >= v4 has a different behavior of force killing the process, the last commit adds the `--exit` behavior to act in pre v4 mode. This typically indicates that there are unresolved tests, which run forever and do not properly quit.
Last but not least, my VSCode setup went crazy without a proper editorconfig, so I've created one to my best second guess efforts. Most of …
> Fix dependency vulnerabilities

- .travis.yml
all node_modules should be cached with yarn workspaces, otherwise yarn redownloads everything
> fix travis caching

- example/src/client.ts
- server/package.json
- server/src/commands.ts
- server/src/completion.ts
- server/src/diagnostic-queue.ts
- server/src/lsp-client.ts
- server/src/lsp-server.spec.ts
- server/src/lsp-server.ts
- server/src/organize-imports.ts
- server/src/protocol-translation.ts
- server/src/quickfix.ts
- server/src/refactor.ts
- server/src/test-utils.ts
- server/src/tsp-client.ts
- server/src/tsp-command-types.ts
- yarn.lock
This PR contains the following improvements:
- diagnostics interruption to improve response time for other requests, as completion and signature help
- applied refactorings support
- suggest diagnostics support
- diagnostics buffering
- tolerating non-file URIs
- organize imports
> various improvements

- README.md
The fix in #40 didn't update the README copy of the usage doc
> Fix typo in usage doc

- example/src/client.ts
- package.json
- server/src/commands.ts
- server/src/lsp-client.ts
- server/src/lsp-server.ts
- server/src/ts-protocol.ts
It is needed to allow clients to track down misbehaving tsservers.
I will open a PR with Theia to try it out.
> allow a client to enable tsserver logging

- server/src/diagnostic-queue.ts
- server/src/lsp-server.spec.ts
- We now create a `debounce` function per open file, so two different files will not 'bounce' the diagnostics for one another.
- I had to use test specific uri's in the tests to prevent the tests from interacting. Even though the tests run in series, they re-use some state (the LSP server) which will causes the tests to interact. Not re-using the state is, I think, not an option because it will slow down the tests.
- Ran the tests
- Tested against an IDE. This CR resolves [this issue](https://github.com/theia-ide/typescript-language-server/issues/70)
> Publish diagnostics for all open files when multiple files are open

- server/src/diagnostic-queue.ts
- server/src/lsp-server.ts
- server/src/protocol-translation.ts
- server/src/quickfix.ts
- server/src/test-utils.ts
This PR makes sure that a server only normalizes URIs for internal computation, but sends responses and notification with client URIs.
It's motivated by https://github.com/atom/ide-typescript/issues/127#issuecomment-421991658
> respect URIs received from clients

- server/src/document-symbol.ts
- server/src/lsp-server.spec.ts
Previously, the documentSymbol results would grow exponentially in size when using multiple elements with the same name such as in some of the examples [for declaration merging](https://www.typescriptlang.org/docs/handbook/declaration-merging.html).
Note that this implementation, although in line with the existing implementation, is different from what VSCode does. An example, given the code:
```
interface Box {
height: number;
width: number;
}
interface Box {
scale: number;
}
```
VSCode will show:
```
Box
height
width
scale
```
While this implementation shows:
```
Box
height
width
Box
scale
```
> Let documentSymbol return the correct results when mergeable elements are used

- .vscode/launch.json
- .vscode/settings.json
- README.md
- package.json
- server/src/calls.ts
- server/src/lsp-connection.ts
- server/src/lsp-protocol.calls.proposed.ts
- server/src/lsp-server.spec.ts
- server/src/lsp-server.ts
- server/test-data/do.ts
- server/test-data/foo.ts
- yarn.lock
This PR add the implementation for the proposed `textDocument/calls` request.
Protocol extension PR: https://github.com/Microsoft/vscode-languageserver-node/pull/420
LSP issue: https://github.com/Microsoft/language-server-protocol/issues/468
> [calls] Initial implementation

- server/src/lsp-server.ts
- server/src/modules-resolver.ts
- server/src/tsp-client.spec.ts
- server/src/tsp-client.ts
Previously, tsserver could only be started as an executable, which would often run the `.bin/tsserver` file that uses a Node shebang to start `tsserver.js` using the first Node on the `$PATH`.
With this PR, tsserver can also be started as a module, by setting `tsserverPath` so it points to `tsserver.js`. Also, when tsserver is bundled with the TS LSP server, it will be started using `cp.fork`, so it uses the same version of Node as the TS LSP server.
This PR is related to https://github.com/theia-ide/typescript-language-server/pull/78
> Allowing starting tsserver as a module using cp.fork

- README.md
- server/src/cli.ts
Also fixes ignoring tsserver logging to file if verbosity was not set.
This was especially confusing since verbosity was not documented. Now a default  of `normal` will be used if verbosity is not set and tsserver logging to file is.
> Add Documentation for TSServer Log Verbosity

- README.md
In the mean time you guys should really redirect all http urls to https and setup a linter to disallow insecure urls to be checked in. 😃
> use https link for typefox.io

- server/src/lsp-server.ts
Closes #94.
I did not provide any additional unit tests as the only realistic setup to reproduce this issue would be when running the test suite on a Windows machine, which is impractical. The change is small and well documented, it's probably not worth it anyway!
> Fix empty documentHighlight results due to inconsistent path delimiters

- README.md
- server/src/lsp-server.ts
`tsserver` can provide options to turn of logging. And for most use cases it is recommended to [turn off  logging.](https://github.com/microsoft/TypeScript/issues/30967)
This PR enables that option.
Thanks.
> Update command line option tssserver-log-verbosity: off will disable logging 

- server/src/lsp-server.ts
- server/src/tsp-client.ts
Fixes https://github.com/eclipse-theia/theia/issues/6720
In order to get better code intelligence for "inferred" projects,
tsserver supports a "compilerOptionsForInferredProjects" command that
informs the TypeScript compiler about how files should be compiled.
This mimicks what the VS Code client does just after calling
"configure" (https://github.com/microsoft/vscode/blob/58d954737facf9478a8255965e5d365bc3d70f71/extensions/typescript-language-features/src/typescriptServiceClient.ts#L479).
Example of better code completion when working on the React sample project (https://code.visualstudio.com/docs/nodejs/reactjs-tutorial):
**Before:**
**After:**
> Call compilerOptionsForInferredProjects during initialization

- server/src/lsp-server.spec.ts
- server/src/lsp-server.ts
LSP warnings don't appear to be actual completion results that are meaningful. This PR removes them from completion results
> Remove warnings from LSP completion results

- .gitignore
- example/package.json
- example/src/client.ts
- server/package.json
- yarn.lock
This cleans up https://github.com/theia-ide/typescript-language-server/pull/156 a bit, especially by cleaning tsbuildinfo files, which can cause typescript compilation errors
> TypeScript upgrade PR fixes

- server/src/tsp-client.ts
- server/src/utils.ts
I'm trying to investigate https://github.com/apexskier/nova-typescript/issues/91, and discovered a potential issue that this fixes. If a typescript server request times out _after_ being cancelled, I think the timeout can still cause an unhandled rejection. I haven't found a real reproduction, so this is purely theoretical.
This fixes that by adding a `cancel` method to the `Deferred` utility that clears the timeout timer.
I also added a few type-only improvements (removing an unused export and some `any`s).
This conflicts a bit with https://github.com/theia-ide/typescript-language-server/pull/92, and can be closed if that one is merged (closed by #92).
> Ensure TSP request cancellation cancels timeout handling

- .gitignore
- .travis.yml
- example/package.json
- example/src/client.ts
- package.json
- server/package.json
- server/src/calls.ts
- server/src/lsp-server.spec.ts
- server/src/lsp-server.ts
- server/src/tsp-client.spec.ts
- yarn.lock
Bumping some basic dependencies. Running into an issue currently where the bumped `lerna` version appears to randomly fail but not report the build failure
> Bump dependencies

- server/src/lsp-server.ts
- server/src/tsp-client.ts
- server/src/utils.ts
Removes timeouts from `Deferred`, because clients can choose to cancel long-running operations if they need to.
This is the same as #92 with merge conflicts resolved.
> Remove hardcoded request timeouts

- server/src/lsp-server.ts
- server/src/ts-protocol.ts
This PR adds an optional `preferences` property to the initialization options that is forwarded through to the tsserver, allowing [user preferences](https://github.com/microsoft/TypeScript/blob/703c1bc69d37ea35d0ba7c58d7632e9ba97c5d94/src/server/protocol.ts#L3313) like `importModuleSpecifierPreference`  to be set.
* Based off of the implementation by @rmagatti and discussion in https://github.com/theia-ide/typescript-language-server/pull/207 🙌 
* Should  also address https://github.com/theia-ide/typescript-language-server/issues/143
---
Tested to work locally with neovim and lsp-config given this config:
```lua
nvim_lsp.tsserver.setup {
init_options = {
preferences = {
importModuleSpecifierPreference = "relative"
}
}
}
```
> Forward user preferences in initialization options

- package.json
- server/src/completion.ts
- server/src/document-symbol.ts
- server/src/hover.ts
- server/src/lsp-server.spec.ts
- server/src/lsp-server.ts
- server/src/protocol-translation.ts
- server/src/tsp-command-types.ts
- server/src/utils.ts
- yarn.lock
This updates the project's TypeScript version from version 3.9.0 to 4.3.4.
I'm working on this in the context of https://github.com/apexskier/nova-typescript/issues/273, because I need to update types to properly type the `skipDestructiveCodeActions` arg.
There were fewer changes than I'd expect, here are the highlights:
* Several types in the tsserver protocol are now `string | tsp.SymbolDisplayPart[]` instead of `string`. I was originally playing with improving the formatting here, but decided not to include that in the scope of this change. (although I'd like to make some improvements separately)
* There are several new command types, so I've updated `server/src/tsp-command-types.ts`
Along with automated tests, I've been manually testing this underneath …
> Update internal Typescript dependency from 3.9.0 to 4.3.4

- server/src/lsp-server.spec.ts
- server/src/lsp-server.ts
- server/src/test-utils.ts
Ensure that diagnostics are only published if client supports the
textDocument.publishDiagnostics capability.
Relates to #191
> Only publish diagnostics if client supports the capability

- server/src/diagnostic-queue.ts
- server/src/lsp-server.spec.ts
- server/src/lsp-server.ts
- server/src/protocol-translation.ts
- server/src/test-utils.ts
Needed to pass client capability down the chain so that we don't add tags when client doesn't support them.
There are more fields on diagnostics that are only supported in later versions (not supported in current code base) so this will also be useful in the future.
@apexskier
> Add support for "unnecessary" and "deprecated" diagnostic tags

- server/src/lsp-server.ts
- server/src/tsp-client.ts
Lookup the tsserver script through a more explicit typescript/lib/tsserver.js
path rather than through the alias created in the ".bin" directory. This
in theory is less future proof as the path to tsserver could change but
in practice it likely never will. And we also had other code paths
(yarn sdk lookup or lookup within this server's package) that used that
approach already so this unifies things more.
The side-effect of doing that is that we'll use "child_process.fork"
rather than "child_process.spawn" for starting the tsserver but we've
done that in other cases already and it seems like a better approach
anyway as then ENV will be inherited from the parent process (haven't
really verified that).
Also it fixes a corner case like #217 where "tsc" package is used and
makes the server …
> Lookup tsserver using direct path rather than through .bin alias

- server/src/completion.ts
- server/src/lsp-server.spec.ts
- server/src/lsp-server.ts
- server/src/test-utils.ts
The deprecated options "includeExternalModuleExports" and "includeInsertTextCompletions" are now passed as global, non-deprecated typescript preferences.
To achieve that, added those as default preferences to the preferences object that the user can override.
Also switch to non-deprecated "CompletionInfo" request and handle "isIncomplete" flag (it is used when suggesting global import completions when `includeCompletionsForImportStatements` and `includeCompletionsWithInsertText` typescript preferences are enabled) and fix some Completion-related types (use LSP types instead of TSC types).
@apexskier
> Don't pass deprecated options to Completion request

- src/protocol-translation.ts
The Windows paths like "C:\\foo" will not cause "URI.parse" to throw
but instead will create an invalid URI. Change to code to only use
URI.parse for zipfile: paths specifically.
> Fix Windows path regression introduced in #220

- src/diagnostic-queue.ts
- src/lsp-server.spec.ts
- src/lsp-server.ts
- src/protocol-translation.ts
Apparently the diagnostics existed before the publishDiagnostics
capability so it's correct to send those in all cases.
Reverts #229
> Send diagnostics even to clients that don't signal support

- .eslintrc.js
- src/commands.ts
- src/completion.ts
- src/lsp-server.ts
Until now, the APPLY_COMPLETION_CODE_ACTION had to be implemented by
each client separately.
> Handle the APPLY_COMPLETION_CODE_ACTION command internally

- README.md
- src/completion.ts
- src/lsp-server.spec.ts
- src/lsp-server.ts
- src/tsp-command-types.ts
For completions that import from another package, the completions
will include a "detail" field with the name of the module.
Also aligned some other logic with the typescript language services used in VSCode:
- annotate the completions with the local name of the import when
completing a path in `import foo from '...'`
- update completion `sortText` regardless if the completion "isRecommended"
Fixes #280
> feat: include import specifier for import completions

- README.md
- src/cli.ts
- src/tsp-client.ts
We want to be able to notify the user about some things without
having to use an error-like messages.
This will come useful in later PR that adds information about used
typescript version.
> fix: change default log level from "warn" to "info"

- README.md
- src/lsp-server.ts
Set the following additional options by default:
allowRenameOfImportPath: true,
displayPartsForJSDoc: true,
generateReturnInDocTemplate: true,
includeAutomaticOptionalChainCompletions: true,
includeCompletionsForImportStatements: true,
includeCompletionsWithSnippetText: true,
This aligns more with the default options of the typescript language
services in VSCode.
> feat: update default typescript options

- README.md
- src/commands.ts
- src/lsp-server.spec.ts
- src/lsp-server.ts
- src/organize-imports.spec.ts
- src/organize-imports.ts
Announcing support for that code action allows editors that support
running code actions on save to automatically run the code action if
the user has configured the editor with settings like
```js
"codeActionsOnSave": {
"source.organizeImports": true,
// or
"source.organizeImports.ts-ls": true,
},
```
> feat: announce support for "source.organizeImports.ts-ls" action

- package.json
This PR fixes a bug in 0.7.0 that prevents `typescript-language-server` from starting due to the `semver` package not being defined as a dependency:
```sh
09:39 $ typescript-language-server --stdio
node:internal/modules/cjs/loader:936
throw err;
^
Error: Cannot find module 'semver'
Require stack:
- /home/ubuntu/.nvm/versions/node/v16.8.0/lib/node_modules/typescript-language-server/lib/utils/api.js
- /home/ubuntu/.nvm/versions/node/v16.8.0/lib/node_modules/typescript-language-server/lib/lsp-server.js
- /home/ubuntu/.nvm/versions/node/v16.8.0/lib/node_modules/typescript-language-server/lib/lsp-connection.js
- /home/ubuntu/.nvm/versions/node/v16.8.0/lib/node_modules/typescript-language-server/lib/cli.js
at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
at …
```
> fix: add missing semver dependency

- src/lsp-server.ts
Announcing support for that code action enables it to be used on saving
with editors that support the Code-Action-On-Save functionality but
the way it works is problematic right now because tsserver returns
an edit even if imports are already correct. That results in running
this code action over and over until editor gives up due to a timeout.
This should be fixed either in tsserver or this server by not returning
a code action if nothing is supposed to change. It's not trivial to
fix though.
> fix: don't announce support for codeActionKinds

- src/completion.ts
This was missing, resulting in import completions leaving stray `$1`
around.
> fix: mark import completions as snippets

- README.md
- src/completion.ts
- src/lsp-server.spec.ts
- src/lsp-server.ts
- src/ts-protocol.ts
- src/utils/SnippetString.ts
- src/utils/typeConverters.ts
On resolving a completion item, additional information are pulled and the `insertText` of the completion is updated with an extended snippet.
This unfortunately is not supported by the editor I'm using (ST) due to it being unable to resolve the completion before triggering the completion but it will hopefully work in other editors.
Fixes #198
> feat: add support for snippet completions of method

- README.md
- src/commands.ts
- src/diagnostic-queue.ts
- src/features/fix-all.ts
- src/lsp-server.spec.ts
- src/lsp-server.ts
- src/organize-imports.spec.ts
- src/organize-imports.ts
- src/tsp-client.ts
- src/utils/errorCodes.ts
- src/utils/fixNames.ts
Implements additional code actions that can be triggered using the Code-Actions-On-Save functionality of the editor or through "Source actions" menu.
- `source.addMissingImports.ts` - adds imports for used but not imported symbols
- `source.fixAll.ts` - despite the name, fixes a couple of specific issues: unreachable code, await in non-async functions, incorrectly implemented interface
- `source.removeUnused.ts` - removes declared but unused variables
- `source.organizeImports.ts` (was already supported but renamed the suffix from `ts-ls` to `ts`) - organizes and removes unused imports
Those are not exposed in the normal code action menu that is shown for individual diagnostics. This matches the behavior of VSCode but not sure about COC.
Fixes #235
> feat: implement additional code actions for handling auto-fixing

- src/lsp-client.ts
- src/lsp-server.ts
- src/test-utils.ts
- src/tsp-command-types.ts
Added server-initiated progress that notifies the client when the typescript project is being loaded. This should trigger on initial loading and also on changing project settings in `tsconfig.json`. Basically any time Typescript decides to (re)load the project since it's based on typescript notifications.
Fixes #237
> feat: report progress when loading the project

- src/commands.ts
- src/features/fix-all.ts
- src/lsp-server.spec.ts
- src/lsp-server.ts
- src/organize-imports.spec.ts
- src/organize-imports.ts
- src/utils/types.ts
The matching of "only" code action kind provided by the client was not correct (especially for the "fixall" actions). Imported the `CodeActionKind` class from VSCode and using its matching logic to fix that.
> fix: correct matching of "only" kinds provided by the client

- .github/workflows/ci.yaml
- package.json
- yarn.lock
Allows to watch files for changes and re-run the tests and doesn't
require manual re-build before each test.
> chore(test): run tests through ts-node

- src/lsp-server.ts
Related: https://github.com/jose-elias-alvarez/nvim-lsp-ts-utils/discussions/95
`organizeImport` should respect the formatting options.
> fix: pass format options for organizing import

- package.json
The script also runs when the user installs the package with
`npm -i g typescript-language-server` so we can't use it.
> fix: don't use the postinstall script

- src/lsp-server.ts
Fix delayed `$/progress` begin event (https://github.com/typescript-language-server/typescript-language-server/pull/326). This is a work-around for https://github.com/microsoft/TypeScript/issues/47465. AFAIK, this is how vscode does it too.
Here's a demo of it correctly sending the "Initializing JS/TS language features ..." event.
Here's what I used for testing https://gist.github.com/icholy/23670692d6405e676611fa49081a5f06
> fix: wait for tsserver configuration requests to finish

- src/lsp-server.spec.ts
- src/lsp-server.ts
Auto import doesn't use insertSpaceAfterOpeningAndBeforeClosingNonemptyBraces formatting option
> fix: call configure before completion resolve 

- src/protocol-translation.ts
It appears the `URI.parse()` and `uri.toString()` dance on `zipfile:` URIs is causing escaping that's confusing my Neovim. (specifically the `::` separator, and newer Neovim requires `zipfile:///path...` instead of `zipfile:/path...`) Considering these URIs are (always?) produced by Yarn v2+, I think we can simply trust them without transformation?
> fix: don't transform Yarn zipfile URIs

- src/protocol-translation.ts
Sorry for the churn on this.
With the fix from #384 in place, I was able to follow a type definition from a regular file into a zipfile. But I wasn't able to take a second step / follow any definitions inside *that* file.
Turns out this is quite obvious. The Yarn hook transfoms VsCode-style zip paths sent by tsserver into Vim-style zip paths, and #384 ensured those weren't mangled by typescript-language-server. So, tsserver could hint Vim about a definition somewhere in a zip file, and Vim could open that file. But then, the opposite happens when Vim opens the file: Vim sends a `textDocument/didOpen` (among others) with a Vim-style zip path in the `uri` field, which typescript-language-server was still mangling, and so the Yarn hook is unable to transform that back to a VsCode-style zip …
> fix: don't transform zipfile URIs from Vim

- README.md
- src/lsp-server.ts
Not all users will already have typescript installed (or they may have done something like switching to a new nodejs install via asdf that doesn't have typescript installed). Also since tsserver is a dependency of typescript-language-server I added it to the readme.
Related: https://github.com/typescript-language-server/typescript-language-server/issues/28
Fixes #336
> fix: help users resolve no valid tsserver version error

- package.json
- yarn.lock
> fix: pin old version of LSP libraries for node <14 compatibility

- src/completion.ts
- src/lsp-server.spec.ts
- src/lsp-server.ts
When trying to type a string with a trigger character the autocompletion does not return a testEdit, causing editors to append the text resulting in duplication and unwanted behaviour.
Had a completion result with the following content:
```json
{
"name": "hello/world",
"kind": "string",
"kindModifiers": "",
"sortText": "11",
"replacementSpan": {
"start": {
"line": 9,
"offset": 11
},
"end": {
"line": 9,
"offset": 12
}
}
}
```
Got transformed into:
```json
{
"label":"hello/world",
"kind":21,
"sortText":"11",
"data":{
"file":"/Users/jasper/projects/codesandbox/pitcher/packages/pitcher-agent/workspace/codesandbox/test-sandbox/draft/priceless-curran/pages/_app.tsx",
"line":9,
"offset":12,
"entryNames":[
"hello/world"
]
}
}
```
But the correct one is:
```json
{
"label":"hello/world",
"kind":21, …
```
> fix: completion for strings with trigger character

- src/lsp-server.spec.ts
- src/protocol-translation.ts
- src/test-utils.ts
Typescript appears to be sending 0, 0 ranges when providing edit for
creating new file, even though the positions are supposed to be 1-based.
Fixes #501
> fix apply refactoring returning -1 positions in ranges

- .github/workflows/ci.yaml
This doesn't drop node 12 compatibility (not yet at least) but stops testing node 12.
Feature dependency updates unfortunately will break node 12 support.
> chore(ci): drop node 12 and add node 18 testing

- package.json
- src/lsp-client.ts
- src/test-utils.ts
- src/tsp-client.ts
- yarn.lock
BREAKING CHANGE: LSP libraries updated to match 3.17 spec. Requires minimum Node 14.
> chore(deps)!: update LSP libraries to match 3.17 spec

- .mocharc.yaml
- package.json
- src/file-lsp-server.spec.ts
- src/lsp-server.spec.ts
- src/lsp-server.ts
- src/tsp-client.spec.ts
- src/tsp-client.ts
Remove forced process exit from mocha configuration which was a way to workaround the issue with the server process not being explicitly shut down and destroy tsserver client and lsp server properly.
This can also affect non-test use-cases but hopefully not for the worse.
The issue with the original problem was that:
a) the server didn't cleanly shut itself down
b) whenever the tsserver was closed (either due to `shutdown` call or just crashed) the code would also force-exit the LS server process. This was typically OK but it wasn't clean and could be problematic for those who'd want to use the server programmatically and not force-close their process when server closes.
> fix: handle shutdown lifecycle properly

- src/lsp-server.ts
There was a bug in monaco-languageclient, (droping codeAction provider metadata), which was making this issue invisible.
The issue is now fixed and quickfix code actions are not working anymore with this LSP implementation because it doesn't declare the quickfix codeAction capability, even though it's able to handle them.
> fix: declare quickfix/refactor CodeAction capabilities

- src/lsp-client.ts
- src/test-utils.ts
Remove some unused LspClient interface methods and use helper methods from the LSP lib.
Should not affect functionality.
> refactor: use lsp lib helper methods

- README.md
- package.json
- src/configuration-manager.ts
- src/features/inlay-hints.ts
- src/lsp-server.ts
- yarn.lock
Making sure that `autoImportFileExcludePatterns` is only sent when list is non-empty as empty list would trigger a slightly slower path in TypeScript.
> feat: add support for new features from TypeScript 4.8

- LICENSE
- src/lsp-server.spec.ts
- src/lsp-server.ts
- src/test-utils.ts
- src/tsServer/callbackMap.ts
- src/tsServer/cancellation.ts
- src/tsServer/requestQueue.ts
- src/tsServer/requests.ts
- src/tsServer/server.ts
- src/tsServer/serverError.ts
- src/tsServer/serverProcess.ts
- src/tsServer/spawner.ts
- src/tsp-client.spec.ts
- src/tsp-client.ts
- src/utils/api.ts
Ported a bunch of code from "VSCode typescript features" to enable us to be able to communicate with `tsserver` over IPC instead of `stdio`. IPC is used for tsserver (typescript) versions 4.60+, otherwise the legacy stdio is used.
If this seems like a lot of code to handle that case then yes, it is, but it's part of the plan to align the code as closely as possible with VSCode to be able to support features like #358 without re-inventing the wheel.
> feat: support communicating with tsserver using IPC

- README.md
- src/cli.ts
- src/diagnostic-queue.ts
- src/lsp-connection.ts
- src/lsp-server.ts
- src/test-utils.ts
- src/ts-protocol.ts
- src/tsServer/cancellation.ts
- src/tsServer/server.ts
- src/tsServer/spawner.ts
- src/tsServer/tracer.ts
- src/tsServer/versionProvider.ts
- src/tsp-client.spec.ts
- src/tsp-client.ts
- src/utils/configuration.ts
- src/utils/logger.ts
Enables nicely formatted log messages with tsserver communication delivered through the LSP messages (so visible in editor's log of LSP communication).
> feat: add "tsserver.trace" init option for tracing tsserver

- README.md
- src/cli.ts
- src/lsp-connection.ts
- src/lsp-server.ts
- src/test-utils.ts
- src/ts-protocol.ts
- src/tsServer/logDirectoryProvider.ts
- src/tsServer/spawner.ts
- src/tsp-client.spec.ts
- src/tsp-client.ts
- src/utils/configuration.ts
BREAKING CHANGE: Replace the CLI argument `--tsserver-log-file` with `tsserver.logDirectory` option provided through `initializationOptions` of the `initialize` request.
> feat!: add `tsserver.logDirectory` to initializationOptions

- README.md
- package.json
- src/lsp-server.ts
- src/test-utils.ts
- src/tsServer/spawner.ts
- src/tsServer/versionProvider.ts
- src/tsp-client.spec.ts
- src/utils/logger.ts
A small refactoring of the logger. Mainly to be able to log certain messages like:
```
if (this.isLoggingEnabled(configuration)) {
if (tsServerLogFile) {
this._logger.logIgnoringVerbosity(LogLevel.Info, `<${kind}> Log file: ${tsServerLogFile}`);
} else {
this._logger.logIgnoringVerbosity(LogLevel.Error, `<${kind}> Could not create log directory`);
}
}
```
regardless of what the logging level is set to.
Using new `logIgnoringVerbosity` method for that.
> refactor: logger implementation

- src/completion.ts
- src/lsp-server.spec.ts
Fixes regression for clients that have `insertReplaceSupport` where completing:
```ts
import { readFil }
```
would result in incorrect insert:
```ts
import { readFile } from "fs"; }
```
The TextEdit in this case would be:
```
"textEdit": {
"insert": {
"end": {
"character": 16,
"line": 0
},
"start": {
"character": 0,
"line": 0
}
},
"newText": "import { readFile$1 } from \"fs\";",
"replace": {
"end": {
"character": 18,
"line": 0
},
"start": {
"character": 0,
"line": 0
}
}
}
```
and the problem would be in the `insert` range.
We should not be providing both insert and replace ranges when TS completion entry has its own `replacementSpan` provided as in that case it's the only valid option.
@predragnikolic
> fix: wrong import completion when insert/replace supported

- src/completion.ts
Removed this old code that overridden filterText for bracket accessor completions.
This old code originally came from VSCode and was later replaced there with a quite different code: https://github.com/microsoft/vscode/commit/beb5998ea3d6b4cae43b3a09ecdf11e3bd692667 to fix issue https://github.com/microsoft/vscode/issues/63100
I've tested in ST and don't see the issue that VSCode had so given no evidence that it's needed outside of VSCode, I'm not trying to replicate what they did here.
Also, in ST at least, the results are better without this old code:
Before:
After:
So before this change editor has shown a leading dot which is not really needed or expected.
As a bonus (in ST at least) it makes this case better as we can see that the property is optional:
> fix(completions): remove filterText override for bracket accessor

- README.md
- src/completion.ts
- src/configuration-manager.ts
- src/lsp-server.spec.ts
- src/lsp-server.ts
- src/test-utils.ts
- src/ts-protocol.ts
Server was supposed to create snippet completions on "resolve" for `method` and `function` completion kinds when the `completeFunctionCalls` workspace settings was enabled.
The code that has created the snippet during "resolve" was checking before-mentioned option but the code that initially set the `insertTextFormat` to `Snippet` did not. That meant that with `completeFunctionCalls` disabled, the `method` and `function` completions were set to `Snippet` kind initially but without a chance of being changed to actual snippets during "resolve".
And for editors that can't use resolved values that meant that those would potentially receive completions with unescaped `$` character in them while not actually being actual snippet.
> fix(completions): don't create snippet kind without `completeFunctionCalls`

- src/tsServer/serverProcess.ts
- src/tsServer/spawner.ts
The issue with using IPC communication for communicating with `tsserver` is that if the parent process gets killed then the `tsserver` process does not shut itself down.
This will be re-enabled once the Typescript issue (https://github.com/microsoft/TypeScript/issues/51100) is fixed.
Fixes #599
> fix: disable IPC communication until TypeScript bug is fixed

- README.md
- src/commands.ts
- src/configuration-manager.ts
- src/lsp-server.ts
- src/tsServer/requests.ts
This adds support for the `_typescript.configurePlugin` command which allows clients to dynamically update plugin configuration.  This is useful when configuring global plugins which, since defined via the command line flags, cannot be configured the same way they might when defined in a local `tsconfig.json` file.
An example of this in Neovim which enables the `typescript-styled-plugin` with some configuration changes.
```lua
require("lspconfig").tsserver.setup({
init_options = {
plugins = {
{
name = "typescript-styled-plugin",
location = "..."
}
}
},
on_init = function()
local params = {
command = "_typescript.configurePlugin",
arguments = {
"typescript-styled-plugin",
{
validate = false,
emmet = {
showExpandedAbbreviation = false
}
}
},
}
client.request("workspace/executeCommand", …
```
> feat: add `_typescript.configurePlugin` workspace command

- README.md
- src/cli.ts
- src/tsServer/versionProvider.ts
Previous logic disallowed one to pass full path to an existing tsserver.js like for example a locally built one at `../built/local/tsserver.js`.
> fix: respect user-provided tsserver.js path from `--tsserver-path`

- src/completion.ts
- src/lsp-server.ts
https://github.com/microsoft/vscode/issues/18131
Align with the implementation of vscode:
https://github.com/microsoft/vscode/blob/6215269681d1afe10ddd786567d9753847213229/extensions/typescript-language-features/src/languageFeatures/completions.ts#L280-L299
> fix(completions): don't insert call snippet if already a call

- src/features/inlay-hints.ts
- src/features/source-definition.ts
- src/lsp-server.ts
Allows client to send `$/cancelRequest` request to cancel any previously triggered request. Previously that did nothing.
And related to that, cancel pending diagnostic request and re-request a new one on receiving document change notification.
> feat: support for canceling LSP requests

- .gitignore
- src/completion.ts
- src/lsp-server.spec.ts
- src/lsp-server.ts
- src/utils/typeConverters.ts
fix(#631)
The implementation method refers to the implementation of vscode and volar:
vscode: https://github.com/microsoft/vscode/blob/6c866f92d7646c31bd9286b1cd8b8151c1e5b38e/extensions/typescript-language-features/src/languageFeatures/completions.ts#L100
volar(vue): https://github.com/volarjs/plugins/blob/master/packages/typescript/src/services/completions/basic.ts
> feat: provide filterText property in completions

- src/document.ts
This affected code that read document line (`document.getLine()`) and resulted in last character being missing when triggered for the last line.
The functionality that was using that functionality was folding ranges and completions.
> fix: line offset off by one when at the last line

- src/lsp-connection.ts
- src/lsp-server.spec.ts
- src/lsp-server.ts
Hey! I've been working on a plugin for neovim that automatically applies workspace edits before moving files around. And it does not work with typescript. The problem with `_typescript.applyRenameFile` that edit is applied only after neovim moves the file. 
So I wanted to implement `workspase/willRenameFile` command that returns the edit. We will be then able to preview and apply it if needed.
Closes https://github.com/typescript-language-server/typescript-language-server/issues/665
Closes https://github.com/antosha417/nvim-lsp-file-operations/issues/6
> feat: support `workspace/willRenameFiles` request

- src/completion.ts
Revert parts of #678 that set the `filterText` property. Reasoning in #631.
> fix(completions): don't set `filterText` after all

- README.md
- src/configuration-manager.ts
- src/diagnostic-queue.ts
- src/lsp-server.ts
- src/test-utils.ts
- src/ts-protocol.ts
- src/tsServer/callbackMap.ts
- src/tsServer/server.ts
- src/tsServer/spawner.ts
- src/tsp-client.spec.ts
- src/tsp-client.ts
- src/typescriptService.ts
- src/utils/configuration.ts
Ported code from VSCode that enables two tsserver instances, one for "syntax" requests and one for "semantic" requests. This should ensure that the more expensive requests like semantic tokens or diagnostic computations don't block more acute requests like completions.
The default is to run with syntax and semantic servers enabled.
Resolves #650 (?)
Resolves #675 (?)
> feat: start separate tsServer instance for semantic requests

- README.md
- src/completion.ts
- src/lsp-server.ts
- src/ts-protocol.ts
Include `filterText` in completions by default.
After long discussion in #631 it seems like this is necessary to properly filter completions in VSCode in Emacs and maybe other editors. In Sublime Text, due to it's API limitations, this actually causes issues so also adding `completionDisableFilterText` initialization option to toggle it off.
Fixes #631
> fix(completions): include `filterText` property by default

- src/tsp-client.ts
Don't report an `InternalError` when `tsserver` crashes on handling request. That error code is reserved for JSON-RPC communication so it might be receive more harsh handling from clients.
Fixes #694
> fix: don't report InternalError on tsserver error response

- src/lsp-server.ts
The initial `Using Typescript version` is using the incorrect verbosity level due to a difference between the values of the `LogLevel` enum and `lsp.MessageType`. `lsp.MessageType` is correct, so switching to that will fix it.
I can also update the `LogLevel` enum to set the same values as the lsp log levels if you'd like.
> fix: verbosity of the "Using Typescript version" message

- README.md
- src/cli.ts
- src/lsp-connection.ts
- src/lsp-server.ts
- src/test-utils.ts
- src/utils/configuration.ts
Remove `--tsserver-path` and `--tsserver-log-verbosity` CLI arguments which were deprecated and should be used through equivalent `tsserver` options in `initializationOptions`.
This was really meant to be done on making the last major (v4) release but I forgot so will sneakily include it for 4.1.
> refactor: remove deprecated CLI options

- src/ts-protocol.ts
- src/utils/tsconfig.ts
Following the fix for https://github.com/microsoft/vscode/issues/196554
> fix: revert to `Node` value for `moduleResolution` in implicit config

- src/ts-client.ts
Errors during tsserver request handling were triggering an unhandled exception and subsequently cause the language server process to exit. Make sure that the promise that is "forked" is also catching exception so that exceptions are caught. The tsserver is able to keep running on error so we can keep running also.
It seems like in vscode the extension process has global handler for unhandled exceptions so even though it doesn't use `catch` on that promise, it still catches the exception and doesn't crash.
Resolves #803 (kind of)
> fix: avoid triggering unhandled exception when tsserver crashes

- src/lsp-server.spec.ts
- src/lsp-server.ts
- test-data/module3.ts
- test-data/rename1/var.ts
typescript-language-server does support willRenameFiles on `folder` but it only provides filter for `file`, other servers like rust-analyzer explicitly specify this filter. The absence of this filter also causes issues in willRenameFiles implementation on the client side if the client only tracks things specified by the filters, i.e it doesn't send requests on folder renamed.
> fix: add folder filter in server capabilities for `willRename`

- docs/configuration.md
- src/lsp-server.ts
- src/ts-protocol.ts
In order to support the broad variety of projects that replit users encounter, we at replit have been [explicitly passing the `typescript` package from `nixpkgs` to `typescript-language-server`](https://github.com/replit/nixmodules/blob/fe25c7a40ef8aa677493c8b7a49d13f04688902c/pkgs/modules/typescript-language-server/default.nix#L20) since April of last year. This has the unfortunate side-effect of not using the `tsserver` that's available in the user's workspace, which means the user may get inaccurate results in their completions.
This PR introduces a new option to `initializationOptions.tsserver`, `fallbackPath`. It has similar semantics to `initializationOptions.tsserver.path`, but is checked if
1. `typescript` passed via `initializationOptions.tsserver.path` is absent or invalid
2. …
> add tsserver.fallbackPath to initialization options

- src/ts-client.ts
Don't create loading progress indicator synchronously during `initialize` request as it's against the spec. It will be created later from tsserver's `projectLoadingStart` event.
Fixes #845
> fix: avoid sending window/workDoneProgress/create before init

- src/diagnostic-queue.ts
diagnostics would malfunction for a file that was closed and later re-opened
> fix: out of date diagnostics after closing and re-opening a file

- src/diagnostic-queue.ts
When diagnostic count was 0 in the previous update and is still 0 then there is no need to send update notification.
> perf: skip diagnostic update event on no changes

- src/utils/previewer.test.ts
- src/utils/previewer.ts
When interpreting the preview result as Markdown, it is quite helpful to have the `typescript` language annotation before `@example` code blocks because it will give code highlights and make it more clear that this is an example of code rather than just raw text.
> fix(previewer): mark `@example` and `@default` code blocks as TS

- .editorconfig
This matches the indentation in .github/workflows/*.yaml files
> style: set editorconfig indentation for yaml files to 2 spaces

- package.json
Set the packageManager field in the package.json file to `yarn@1` to make the development environment easier to reproduce.
Some tools, like corepack (and yarn itself?) will use this field to use the correct package manager version
https://yarnpkg.com/configuration/manifest#packageManager
> chore: set packageManager field to yarn@1.x
